apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-agent
  namespace: acdt
spec:
  project: default
  source:
    repoURL: 'https://github.com/ovbytes/appdy-argo-ca.git'
    targetRevision: HEAD
    path: "."
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: omvelazq
