cluster-agent:
  installClusterAgent: true

  controllerInfo:
    url: https://ces-controller.saas.appdynamics.com:443
    account: "secret://controller-secrets:account"
    accessKey: "secret://controller-secrets:accessKey"

  clusterAgent:
    nsToMonitorRegex: .*  # Cambia esto según el namespace que deseas monitorizar
  serviceAccountName: appdynamics-cluster-agent  # Name of your ServiceAccount
  secretName: cluster-agent-secret  # Name of the Secret
