cluster-agent:
  installClusterAgent: true

  controllerInfo:
    url: "secret://controller-secrets:url"
    account: "secret://controller-secrets:account"
    accessKey: "secret://controller-secrets:accessKey"

  clusterAgent:
    nsToMonitorRegex: .*  # Cambia esto según el namespace que deseas monitorizar
  serviceAccountName: appdynamics-cluster-agent  # Nombre del ServiceAccount
  secretName: cluster-agent-secret  # Nombre del Secret
