cluster-agent:
  # Activa la instalación del Cluster Agent
  installClusterAgent: true

  # Configuración del agente del clúster
  clusterAgent:
    nsToMonitorRegex: .*  # Cambia esto según el namespace que deseas monitorizar

  # Otras configuraciones de instalación (como metrics-server)
  #install:
  #  metrics-server: true
